# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              'roachhaus.github.io/run-jekyll-on-windows/'
baseurl:          '/run-jekyll-on-windows/'

github:
  repo:           https://github.com/roachhaus/run-jekyll-on-windows

author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball
