# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              roachhd.github.io/run-jekyll-on-windows/
baseurl:          /run-jekyll-on-windows/

github:
  repo:           https://github.com/roachhd/run-jekyll-on-windows

author:
  name:           'Katie Ball'
  url:            https://twitter.com/mektball
